class(eagle,bird).
class(shark,fish).
class(t_rex,reptile).
class(lizard,reptile).
class(trout,fish).
class(dolphin,mammal).
class(eagle,bird).
class(eagle,bird).
class(dog,mammal).
class(crocodile,reptile).
class(cat,mammal).
class(snake,reptile).
class(eagle,bird).
class(turtle,reptile).
class(turtle,reptile).
class(crocodile,reptile).
class(eagle,bird).
class(t_rex,reptile).
class(shark,fish).
class(crocodile,reptile).
class(trout,fish).
class(penguin,bird).
class(bat,mammal).
class(turtle,reptile).
class(shark,fish).
class(platypus,mammal).
class(bat,mammal).
class(shark,fish).
class(eel,fish).
class(eagle,bird).
class(snake,reptile).
class(ostrich,bird).
class(ostrich,bird).
class(turtle,reptile).
class(ostrich,bird).
class(snake,reptile).
class(cat,mammal).
class(snake,reptile).
class(ostrich,bird).
class(ostrich,bird).
class(shark,fish).
class(t_rex,reptile).
class(t_rex,reptile).
class(shark,fish).
class(cat,mammal).
class(eagle,bird).
class(cat,mammal).
class(lizard,reptile).
class(eel,fish).
class(herring,fish).
class(eagle,bird).
class(dolphin,mammal).
class(t_rex,reptile).
class(cat,mammal).
class(cat,mammal).
class(platypus,mammal).
class(eel,fish).
class(cat,mammal).
class(trout,fish).
class(penguin,bird).
class(dolphin,mammal).
class(platypus,mammal).
class(herring,fish).
class(penguin,bird).
class(shark,fish).
class(bat,mammal).
class(herring,fish).
class(trout,fish).
class(lizard,reptile).
class(dolphin,mammal).
class(platypus,mammal).
class(shark,fish).
class(lizard,reptile).
class(trout,fish).
class(eagle,bird).
class(herring,fish).
class(bat,mammal).
class(snake,reptile).
class(herring,fish).
class(snake,reptile).
class(dog,mammal).
class(herring,fish).
class(eagle,bird).
class(eel,fish).
class(dog,mammal).
class(eel,fish).
class(lizard,reptile).
class(cat,mammal).
class(crocodile,reptile).
class(t_rex,reptile).
class(snake,reptile).
class(snake,reptile).
class(eagle,bird).
class(shark,fish).
class(herring,fish).
class(t_rex,reptile).
class(dolphin,mammal).
class(t_rex,reptile).
class(shark,fish).
class(cat,mammal).
class(ostrich,bird).
class(turtle,reptile).
class(eagle,bird).
class(platypus,mammal).
class(eagle,bird).
class(turtle,reptile).
class(platypus,mammal).
class(cat,mammal).
class(dolphin,mammal).
class(shark,fish).
class(cat,mammal).
class(ostrich,bird).
class(eagle,bird).
class(dog,mammal).
class(cat,mammal).
class(shark,fish).
class(lizard,reptile).
class(penguin,bird).
class(platypus,mammal).
class(cat,mammal).
class(platypus,mammal).
class(dolphin,mammal).
class(bat,mammal).
class(dog,mammal).
class(ostrich,bird).
class(lizard,reptile).
class(penguin,bird).
class(ostrich,bird).
class(lizard,reptile).
class(herring,fish).
class(penguin,bird).
class(lizard,reptile).
class(platypus,mammal).
class(dog,mammal).
class(turtle,reptile).
class(eagle,bird).
class(penguin,bird).
class(snake,reptile).
class(dolphin,mammal).
class(shark,fish).
class(cat,mammal).
class(shark,fish).
class(lizard,reptile).
class(trout,fish).
class(lizard,reptile).
class(herring,fish).
class(snake,reptile).
class(shark,fish).
class(bat,mammal).
class(dolphin,mammal).
class(turtle,reptile).
